server:
  port: 8080

spring:
  application:
    name: coupon-api
  cache:
    type: simple

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

coupon-api:
  cache-ttl-minutes: 30
